name: flutter_expense_tracker
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^5.0.0
  http: ^1.2.2
  shared_preferences: ^2.3.4
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  coverage: ^1.11.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/hinh1.png
    - assets/icons/